- Dockerfile
Currently pushing this to quay.io/dukegcb/bespin-lando
> Adds Dockerfile for running in production

- setup.py
> setup.py requirement of requests 2.18.1

- lando/server/cloudservice.py
- lando/server/config.py
- lando/server/jobapi.py
- lando/server/lando.py
- lando/server/tests/test_cloudservice.py
- lando/server/tests/test_jobapi.py
- lando/server/tests/test_lando.py
Creates a cinder volume for each worker so they can be flexible about how much space to use.
> Allow jobs to customize VM volume size

- integration_test/setup.py
- lando/worker/cwlworkflow.py
- lando/worker/tests/test_cwlworkflow.py
- lando/worker/tests/test_worker.py
- lando/worker/worker.py
- setup.py
> Renames input_json -> job_order

- Dockerfile
lando-messaging is installed in setup.py
> Remove pip install lando-messaging.git from Dockerfile

- lando/server/lando.py
- setup.py
Fix for bad file name reported in #55
> Fix worker config filename

- lando/server/lando.py
- Restore lando server config filename
- Correctly fix worker config filename
> Previous commit changed the wrong filename

- lando/server/cloudservice.py
- lando/server/tests/test_cloudservice.py
> Fix create volume shade call

- setup.py
This version includes retries for swift 401 unauthorized among other fixes
> Update required DukeDSClient to 0.3.18

- lando/worker/cwlreport.py
- lando/worker/tests/test_cwlreport.py
> Support for class=Directory job output

- setup.py
This contains logic to retry for the weekly DukeDS downtime
> upgrade to DukeDSClient 0.3.20

- integration_test/setup.py
- lando/server/jobapi.py
- lando/server/tests/test_jobapi.py
- lando/server/tests/test_lando.py
- lando/worker/tests/test_worker.py
Depends on https://github.com/Duke-GCB/bespin-api/pull/102
> Updates jobapi to use job-dds-output-projects instead of job-output-dir

- circle.yml
- lando/worker/staging.py
- lando/worker/tests/test_staging.py
- setup.py
Upgrading DukeDSClient version caused this issue
Fixes #93
> Change project_name share parameter to project

- README.md
> Update README to indicate that vm_settings now go in bespin-api

- setup.py
> upgrade PyYAML to 3.12

- lando/server/jobapi.py
- lando/server/lando.py
- lando/server/tests/test_lando.py
> Updates lando server to PUT job step as '' instead of null

- lando/worker/staging.py
- lando/worker/tests/test_staging.py
> Configure lando worker to force sending shares

- lando/worker/cwlworkflow.py
- lando/worker/tests/test_cwlworkflow.py
- lando/worker/tests/test_worker.py
- lando/worker/worker.py
Changes are for the worker as the server already appears to handle this.
> Changes to handle workflows without a methods document

- setup.py
https://nvd.nist.gov/vuln/detail/CVE-2018-18074
> update requests to 2.20.1

- lando/k8s/jobmanager.py
- lando/k8s/tests/test_jobmanager.py
Requires https://github.com/Duke-GCB/lando-util/pull/6
Partially fixes #143. Still need to record when workflow was started and finished.
> Remove job data placeholder value.

- setup.py
> upgrade lando-messaging to fix duplicate share emails

- lando/k8s/jobmanager.py
- lando/k8s/tests/test_jobmanager.py
- lando/k8s/tests/test_lando.py
> fix k8s output project name to match vm job version

- setup.py
> Removes cwlref-runner dependency from setup.py

- lando/common/commands.py
- lando/common/tests/test_commands.py
Fixes bug where StepProcess.run wasn't being called during staging/organize output/upload results commands.
Fixes #201
> fix exit code error

- lando/k8s/README.md
Updates documentation about minimal required permissions needed by the `lando` service account.
Fixes #146
> Update k8s README lando k8s permissions
