Duke-GCB/lando

lando/server/cloudservice.py, lando/server/config.py, lando/server/jobapi.py, lando/server/lando.py, lando/server/tests/test_cloudservice.py, lando/server/tests/test_jobapi.py, lando/server/tests/test_lando.py, lando/worker/tests/test_worker.py, lando/worker/worker.py
Added method to set job step.
Separate job state from job step.
State: NEW, RUNNING, FINISHED, ERRORED, CANCELED
Step: CREATE_VM, STAGING, RUNNING, STORING_JOB_OUTPUT, TERMINATE_VM
Simplified based on using mock in unit tests.
Added method to get jobs based on vm_instance_name for worker_started.
Added method to save errors back to bespin-api.
Added method to get all pages for a url that supports paging.
Rewrote tests to use mock.
CloudService now receives a project name to specify VM allocation/billing.
server.Config now creates cloud credentials based on  project name arg.
Set job step and state.
Changed start job to only create vm (first step).
Added method to handle worker_started to send stage data message (second step).
Added method to handle restart job.
Save errors back to …
=> Job step, cloud project_name, errors and paging support

circle.yml, lando/server/lando.py, lando/server/tests/test_cwlworkflow.py, lando/server/tests/test_lando.py, lando/worker/tests/test_worker.py, setup.py
Places {"job":<id>,"state":<state>,"step":<step>} into job_status exchange.
This will be picked up by bespin-job-watcher and broadcasted to websockets subscribed to this job.
=> Send job progress notifications to rabbit job_status exchange

README.md, lando/server/cloudservice.py, lando/server/config.py, lando/server/tests/test_cloudservice.py, lando/server/tests/test_config.py
Previously floating ip addresses were allocated and not deleted at VM termination.
Now the lando server will delete the floating ip address attached to a VM.
This floating ip is allocated and attached during VM creation.
Fixes #5
Also adds a `allocate_floating_ips` to the `vm_settings` part of `/etc/lando_config.yml` which turns on/off floating ip address allocation.  Creating a floating IP address for each instance VM is not necessary for the worker to perform it's job.
=> Release floating ip

Dockerfile
The current version didn't upgrade lando-messaging to 0.4.
After this change it installs the latest.
=> Docker: install current verison of lando_messaging

lando/server/cloudservice.py, lando/server/tests/test_cloudservice.py, lando/server/tests/test_lando.py, lando/worker/tests/test_cwlworkflow.py, setup.py
Nova keeps changing the API and shade is much simpler for controlling openstack.
shade handles allocating floating IPs internally so we no longer need to manually do that.
Reworks the setup.py requirements (needed specific Babel version for install to work).
Fixed cwl test that broke with cwl-runner changes.
Fixes #25
=> Switching from nova to shade

lando/server/jobapi.py, lando/server/tests/test_jobapi.py
We were still sending the credentials associated with the user who
was running the job. Now that the users use OAuth/DDS credentials
to give the bespin user credentials download permission we need
to send the bespin user credentials.
Fixes #27
=> Send worker bespin admin credentials

README.md, lando/server/jobapi.py, lando/server/tests/test_jobapi.py, lando/worker/staging.py, lando/worker/tests/test_staging.py, lando/worker/tests/test_worker.py, lando/worker/worker.py, setup.py
Changes to transfer project to requesting user after we finish uploading.
Requires changes to (bespin-api)[https://github.com/Duke-GCB/bespin-api] adding username to the AdminJobSerializer.
=> Give project to user

lando/server/jobapi.py, lando/server/tests/test_jobapi.py, lando/worker/cwlworkflow.py
Swaps out __input_file_group__ for __file_stage_group__ to match up with https://github.com/Duke-GCB/bespin-api/pull/40. 
Also fixes a bug where we were checking the exit code from running cwl-runner too late.
=> Rework job building changes

lando/worker/staging.py, lando/worker/tests/test_staging.py
Big "M" is the minute. 
Little "m" is the month.
Somehow had this wrong in the test too.
=> Fix project name to contain year-month-day

lando/worker/cwlreport.py, lando/worker/tests/test_cwlreport.py
Recursively go through files in the cwltool output file.
Also adds secondaryFiles to the report.
Fixes #35
=> Change report to handle nested arrays in cwltool output

setup.py
Fixes #38 
Once https://github.com/common-workflow-language/cwltool/pull/450 is added to a release we can remove this change.
=> Fix so cwlref-runner will install successfully

README.md, lando/server/config.py, lando/server/tests/test_config.py, lando/worker/config.py, lando/worker/cwlworkflow.py, lando/worker/staging.py, lando/worker/tests/test_cwlworkflow.py, lando/worker/tests/test_worker.py, lando/worker/worker.py, setup.py
Previously the workers config file could be modified to allow running a different workflow command.
Changes here let the main __lando__ server config specify what workflow commands workers should use. 
Switching to [cwltoil](https://github.com/BD2KGenomics/toil) because it runs scatter workflows in parallel. Command line is mostly the same just minor tweaks. Stdout is different but we are not parsing this data yet.
Also found a bug where we were trying to call `create_activity` and `share_project` on SaveJobOutput. These are both handled by the SaveJobOutput `run` method now.
=> Changes to use cwltoil to run workflows

lando/server/jobapi.py, lando/server/lando.py, lando/server/tests/test_jobapi.py, lando/worker/staging.py, lando/worker/tests/test_staging.py
During the store output step the lando worker will share the project with every user in the share group. 
NOTE: This requires the lando user to have an email template setup in D4S2.
=> Share resulting project with share group

lando/server/cloudconfigscript.py, lando/server/tests/test_cloudconfigscript.py
- Specifying the device and partition, while documented in http://cloudinit.readthedocs.io/en/latest/topics/examples.html#disk-setup does not work here.
- Instead just specify the partition as the device in fs_setup
I tested the generated configs in a jupyter notebook using shade. This works, and I confirmed the previous configs do not.
=> Update fs_setup section in cloudconfig

lando/worker/cwlworkflow.py
Fixes #64
Replaces loop that reads from stdin/stdout with communicate method in lando worker:
https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate
The loop caused deadlocks with reading stdout: https://docs.python.org/2/library/subprocess.html#subprocess.Popen.stdout
=> Replace stdin/stdout loop with communicate

lando/server/jobapi.py, lando/server/lando.py, lando/server/tests/test_jobapi.py, lando/server/tests/test_lando.py
Also uses job.vm_instance_name for terminating vm consistently (instead of relying on payload.vm_instance_name  in one place).
=> Only terminate vm/volume if cleanup_vm = True

circle.yml, lando/worker/cwlworkflow.py, lando/worker/provenance.py, lando/worker/tests/test_cwlworkflow.py, lando/worker/tests/test_provenance.py, setup.py
Fixes #69 
Old format:
```
README
results/
...output files from workflow
logs/
cwltool-output.json   #stdout from cwl-runner - json job results
cwltool-output.log    #stderr from cwl-runner
job-data.json         # non-cwl job data used to create Bespin-Report.txt
workflow/
workflow.cwl            # cwl workflow we will run
workflow.yml            # job order input file
```
New format:
```
results/
...output files from workflow
documentation/
README
logs/
cwltool-output.json   #stdout from cwl-runner - json job results
cwltool-output.log    #stderr from cwl-runner
job-data.json         # non-cwl job data used to create Bespin-Report.txt
workflow/
workflow.cwl            # cwl workflow we will run
workflow.yml            # job order input file
```
=> reorganize output project based on user feedback

lando/worker/staging.py, lando/worker/tests/test_staging.py
Fixes #73 
We no longer needed to pass url returned by DukeDS to the FileDownloader as it now does that right before it's needed in the latest version of DukeDSClient.
=> Ddsclient upgrade fix

integration_test/worker_config.yml, lando/server/__main__.py, lando/server/config.py, lando/server/lando.py, lando/server/tests/test_config.py, lando/worker/__main__.py, lando/worker/config.py, lando/worker/cwlworkflow.py, lando/worker/staging.py, lando/worker/tests/test_config.py, lando/worker/worker.py
Allow server and worker config to specify log_level in config file.
The config for both now have an optional top level 'log_level' with the string or int python log level.
The server will write the logging to stdout.
The worker will write logging to `/tmp/lando-worker.log`.
Also fixes a bug in saving the output project for DukeDSClient changes.
=> Configurable logging

lando/server/cloudconfigscript.py, lando/server/lando.py, lando/server/tests/test_cloudconfigscript.py, lando/server/tests/test_lando.py
Also adds some more comprehensive tests around lando.server.launch_vm
Fixes #79
=> Include `manage_etc_hosts` in cloud-config script

lando/worker/cwlworkflow.py, lando/worker/tests/test_cwlworkflow.py
Only send the last 5000 lines of stderr to bespin-api for failed jobs.
=> limit stderr data sent to bespin-api for failed jobs

integration_test/setup.sh, lando/server/jobapi.py, lando/server/lando.py, lando/server/tests/test_jobapi.py, lando/server/tests/test_lando.py, lando/worker/cwlreport.py, lando/worker/cwlworkflow.py, lando/worker/scriptsreadme.py, lando/worker/staging.py, lando/worker/tests/test_cwlreport.py, lando/worker/tests/test_cwlworkflow.py, lando/worker/tests/test_scriptsreadme.py, lando/worker/tests/test_staging.py, lando/worker/tests/test_worker.py, lando/worker/worker.py
Adds readme file id to PUT request to `job-dds-output-projects/<id>/` that already saves the project id. Also adds markdown README files.
Fixes #78
=> save readme file id to bespin-api job output project

lando/server/config.py, lando/server/tests/test_config.py, lando/worker/config.py, lando/worker/cwlworkflow.py, lando/worker/tests/test_config.py, lando/worker/tests/test_cwlworkflow.py, lando/worker/tests/test_worker.py, lando/worker/worker.py
Adds `cwl_post_process_command` array option to the lando server configuration.
This option is sent to the worker's config. The command is run once the CWL workflow succeeds and the output directory tree is created. The `cwl_post_process_command` will execute from within the `results` directory. After `cwl_post_process_command` is run the directory will be uploaded to DukeDS in the next step.
=> cwltoil temp dir fix

lando/worker/cwlreport.py, lando/worker/tests/test_cwlreport.py
Recursively looks through dictionaries until a `path` key is found.
Fixes #96
=> Update cwlreport to handle custom objects containing files

lando/worker/cwlreport.py, lando/worker/cwlworkflow.py, lando/worker/tests/test_cwlreport.py
Use codecs.open to read/write files for marking encoding to markdown rendering
Fixes #98
=> Fix render unicode

lando/server/cloudservice.py, lando/server/config.py, lando/server/jobapi.py, lando/server/lando.py, lando/server/tests/test_cloudservice.py, lando/server/tests/test_config.py, lando/server/tests/test_jobapi.py, lando/server/tests/test_lando.py, lando/worker/config.py
Updates lando server to read VM settings like project, flavor, volume_mounts, volume_size, etc from Job rather than config.
- Requires https://github.com/Duke-GCB/bespin-api/pull/120 for changes to Job payload
- Removes the default VM flavor, since every job will specify the flavor
- Adds pre-processing command for CWL (e.g. make required directories)
- lando worker still reads its job-specific config (e.g. cwl command) from a config file, since the worker VM is job-specific and it does not communicate with bespin API
Fixes #92
=> server: read vm_settings per Job rather than global config

lando/server/lando.py, lando/server/tests/test_lando.py
Adds try/except around handling exceptions raised by job actions.
Adds some additional logging so we record the error even if we are unable to access bespin api.
Fixes #105
=> trap job action error handling exceptions

setup.py
upgrading lando-messaging to version that has heartbeat turned on
for lando worker it will disconnect before processing messages
This fix is related to the issue here: to https://github.com/Duke-GCB/bespin-mailer/issues/1
=> heartbeat fix

setup.py
Fixing bug where lando was using the old D4S2 url.
Upgrading DukeDSClient will start using the new the D4S2 url: `datadelivery.genome.duke.edu`.
Upgrading to latest minor version of shade to fix installation issue with circleci.
=> Fix D4S2 url bug

setup.py
Fix to work around error when building lando worker image:
```
Found existing installation: PyYAML 3.11\n\n:stderr: Cannot uninstall 'PyYAML'. 
It is a distutils installed project and thus we cannot accurately determine which files 
belong to it which would lead to only a partial uninstall
```
=> switch to PyYAML 3.11

lando/server/jobapi.py, lando/server/lando.py, lando/server/tests/test_lando.py
Fixes issue where the terminate vm step has an error and the user chooses to restart the job.
The terminate vm step must first save the project id and readme file id back to bespin api.
To handle this problem in this fix we restart the process at storing output step.
Fixes #118 
Requires https://github.com/Duke-GCB/bespin-api/pull/150
=> better handle restart after failed terminate VM

lando/worker/cwlworkflow.py, lando/worker/tests/test_cwlworkflow.py
Rather than piping logs in-memory to the lando_worker process, this change redirects stdout and stderr to files in temp directories, then copies those files to the output directory on completion.
This change has the following benefits:
- While workflows are running under cwltool, stderr should be viewable from the VM (as they have been with toil)
- Streaming logs back to bespin should be possible, since they can be viewed from a file
- stderr output can be written natively without having to be read through codecs
=> Reconfigures CWL subprocess to log to local files

setup.py
Verified lando_worker_image builds in openstack with this PyYAML 3.12 requirement.
Fixes #131
=> Switch to PyYAML 3.12 for compat with openstacksdk

lando/exceptions.py, lando/k8s/cluster.py, lando/k8s/config.py, lando/k8s/jobmanager.py, lando/k8s/tests/test_cluster.py, lando/k8s/tests/test_config.py, lando/k8s/tests/test_jobmanager.py, setup.py
Changes removed from #139 to simplify the review process.
Adds a `k8s` module under `lando` consisting of:
- `ServerConfig` config file for k8s version of lando
- `ClusterApi` class for simplifying interacting with k8s
- `JobManager` class that uses `ClusterApi` to create volumes and run jobs for various steps of running the job.
The `JobManager` has methods for creating jobs for the following job steps:
https://github.com/Duke-GCB/lando/blob/f8b661fb6becb00e3f98f866537dba662cc63ebf/lando/k8s/jobmanager.py#L15-L19
For each job step handled by `JobManager` there are at most 3 methods:
- a method to setup volumes before running the job. eg:  [create_stage_data_persistent_volumes](https://github.com/Duke-GCB/lando/blob/f8b661fb6becb00e3f98f866537dba662cc63ebf/lando/k8s/jobmanager.py#L65)
- …
=> k8s job manager changes

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py, lando/k8s/tests/test_lando.py
Usernames from bespin api contained email addresses. This caused failures creating various k8s objects due the names containing `@` and `.`. To clean this up I am stripping everything after after and including `@` in the username provided by the bespin api job details.
Fixes #147
=> Sanitize k8s names

lando/k8s/README.md, lando/k8s/config.py, lando/k8s/jobmanager.py, lando/k8s/tests/test_config.py, lando/k8s/tests/test_jobmanager.py, lando/server/cloudservice.py, lando/server/jobapi.py, lando/server/lando.py, lando/server/tests/test_cloudservice.py, lando/server/tests/test_jobapi.py, lando/server/tests/test_lando.py
Removes k8s step config settings for image name, base command, cpus, memory.
Adds code to read k8s step config(image name, base command, cpus, memory) from bespin-api v2 job payload.
Changes to update parsing job response due to bespin-api v2 changes.
=> Use bespin-api v2 for k8s support

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py, lando/server/jobapi.py, lando/server/tests/test_jobapi.py
When running the workflow pass the memory and cores values from job flavor to `--max-ram` and `--max-cores`.
Requires https://github.com/Duke-GCB/calrissian/issues/52
Fixes #158
=> pass job cpu/memory to calrissian

lando/server/jobapi.py, lando/server/tests/test_jobapi.py
Removes no longer needed JSON deserialization for `v2` API.
Fixes #160
=> remove json.load from CWL command parsing

setup.py
Adds nested `pyasn1` requirement as top level requirement from `pyasn1-modules`. 
This is to avoid issue where older version of pyasn1 ends up installed that is incompatible with `pyasn1-modules` requirements. 
Fixes #162
=> add pyasn1 top level requirement

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py
Extends the k8s JobManager to include the `--usage-report` argument, e.g.
```
--usage-report /bespin/output-data/job-51-jpb-resource-usage.json
```
Fixes #166
=> Add calrissian argument to write usage report

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py
Implements changes to record provenance data for k8s jobs using https://github.com/Duke-GCB/lando-util/issues/3
During the staging data step we record the downloaded files metadata into a file.
During the upload step we pass data in to specify the activity to be created.
=> k8s job should record provenance data

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py
Makes use of feature added to lando-util on https://github.com/Duke-GCB/lando-util/pull/19 to include the usage report in the output logs.
=> add usage report to resulting project logs

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py
Use calrissian --stdout and --stderr flags to save stdout/stderr to files and print them so they will be picked up by the pod logs.
Requires https://github.com/Duke-GCB/calrissian/releases/tag/0.4.0
Fixes #149
=> populate run workflow pod logs

lando/k8s/config.py, lando/k8s/jobmanager.py, lando/k8s/tests/test_config.py, lando/k8s/tests/test_jobmanager.py
Adds `tmp_volume_size_in_g` value to the k8s lando config file. 
If not specified `tmp_volume_size_in_g` will default to 10.
This value will replace the hard coded 1G size used for `/tmp` when running a workflow.
Part of #141
=> allow configuration of tmp via lando config file

lando/k8s/config.py, lando/k8s/jobmanager.py, lando/k8s/lando.py, lando/k8s/tests/test_config.py, lando/k8s/tests/test_jobmanager.py, lando/k8s/tests/test_lando.py, lando/server/jobapi.py, lando/server/tests/test_jobapi.py
Determines size of the job-data volume based on the size of the input data + a config setting base size. The setting base size is a new config file setting called `base_stage_data_volume_size_in_g `.
Removes the tmp and tmpout volumes. The workflow runner job will now be provided a single ouput-data volume and flags to use directories inside that volume for output data and tmpout.
The tmpout directory will now be `/bespin/output-data/tmpout`.
Fixes #141
=> k8s volume improvements

lando/k8s/lando.py, lando/k8s/tests/test_lando.py
Previously the code was converting bytes to MiB instead of GiB.
This resulted in enormous job data volumes.
Fixes #177
=> fix job input data gb conversion

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py
Canceling one k8s job canceled all k8s jobs.
This was due to a label selector that was missing the job id.
Tested these changes on dev. I was able to cancel a job without effecting another running job.
Fixes #176
=> Fix job cancellation

.circleci/config.yml, setup.py
- Updates CircleCI config to build+deploy, verified in a [fork](https://github.com/dleehr/lando)
- Deploy includes code to verify version in setup.py matches the tag being released
- Deploy uploads `lando` to PyPI. I manually uploaded 0.9.14 from a local build off the tag
- After merging this and other changes today, we can tag/release 0.9.15
Fixes #179
=> Upload releases to PyPI, verify version matches tag

lando/worker/cwlworkflow.py, lando/worker/tests/test_cwlworkflow.py
- Needed another field to keep this separate from the command-line runnable workflow and the file name to use in the README
- Slightly different between packed and zipped. Worked for zipped workflows but needed a version without #main for packed
Fixes #189
=> Adds field for the workflow file to read when loading info

lando/server/tests/test_cloudconfigscript.py, lando/server/tests/test_lando.py, lando/worker/staging.py, lando/worker/tests/test_staging.py, setup.py
- Upgrades DukeDSClient to 2.1.4 which has support for the S3 backend.
- Changed the download logic to match [lando-util](https://github.com/Duke-GCB/lando-util/blob/8e8c8d967a82a056d85a7b0bdf51a61b5b8dd603/lando_util/download.py#L27-L28)
- Upgrades PyYAML to 5.1 since it's required by DukeDSClient. This changed a bunch of YAML in tests. In a test the cloud config script seemed to work fine.
- Upgrades Jinja2 to 2.10.1 since there is a security issue with previous version.
=> upgrade DukeDSClient for s3 support

lando/worker/staging.py, lando/worker/tests/test_staging.py
Fixes #193 
Bug introduced in #192.
> I must have accidentally tested that PR with an older bespin worker VM.
=> use correct location for finding size in dukeds file resp

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py, lando/k8s/tests/test_lando.py
Support for zipped workflows
- When staging a zipped workflow specify `unzip_to` option to extract the zipfile
- When organizing the output project pass `downloaded_workflow_path`, `workflow_to_read` and `workflow_type` parameters.
Fixes #188
Requires: https://github.com/Duke-GCB/lando-util/pull/21
=> support for zipped workflows in k8s  jobs

lando/k8s/jobmanager.py, lando/k8s/tests/test_jobmanager.py
Replaces `--tmp-outdir-prefix` flag with `--cachedir` when running a workflow as part of a k8s job.
Fixes #198
=> use cachedir flag when running a workflow in k8s

lando/k8s/lando.py, lando/k8s/tests/test_lando.py
The restart logic was not passing the input files to the perform_staging_step method.
Improves tests to better test the called methods.
Fixes #195
=> fix restart k8s staging

lando/k8s/cluster.py, lando/k8s/tests/test_cluster.py, lando/k8s/tests/test_watcher.py, lando/k8s/watcher.py
The lando k8s job watcher code was attempting to read logs for a failed job by finding a pod with the `job_name`. This failed to find a pod and always returned `Unable to read logs`. Changes here read the logs from the most recent pod created by a failed job.
Fixes 204
=> Fix saving logs from failed jobs
